"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from config import load_config
import logging

config = load_config()

logging.basicConfig(
    level=logging.getLevelName(level=config.log.level),
    format=config.log.format,
    filename="logs.log",
    filemode="w"
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# BASE_DIR = C:\Users\ivan1\Dev\Courses\Django_2_course

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config.django.secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS: list = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',
    'blog',
    'users',
]

MIDDLEWARE = [
    # Безопасность (должен быть одним из первых)
    'django.middleware.security.SecurityMiddleware',

    # Сессии (перед AuthenticationMiddleware)
    'django.contrib.sessions.middleware.SessionMiddleware',

    # Локализация (если используется)
    'django.middleware.locale.LocaleMiddleware',

    # Общие middleware
    'django.middleware.common.CommonMiddleware',

    # CSRF-защита (после SessionMiddleware, до представлений, проверяющих CSRF)
    'django.middleware.csrf.CsrfViewMiddleware',

    # Аутентификация (после SessionMiddleware, т.к. использует сессии для хранения user id)
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    # Сообщения
    'django.contrib.messages.middleware.MessageMiddleware',

    # Защита от кликджекинга
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Здесь можно добавить свои кастомные middleware
    'myapp.middleware.SimpleTimingMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    # "default": {
    #     "ENGINE": "django.db.backends.postgresql",
    #     "NAME": config.db.name,
    #     "USER": config.db.user,
    #     "PASSWORD": config.db.password,
    #     "HOST": config.db.host,
    #     "PORT": config.db.port,
    # }
}
# bash: py -Xutf8 manage.py dumpdata --exclude auth.permission --exclude contenttypes --output data.json
# bash: py manage.py loaddata data.json --database=new


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Для разработки
STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / 'myapp/static/myapp',
]

# Для развертывания
STATIC_ROOT = BASE_DIR / 'staticfiles' # Пример (папку staticfiles нужно будет создать или она создастся автоматически)
# Или: STATIC_ROOT = '/path/to/your/production/static/files/' на реальном сервере


# LOGIN/LOGOUT URLs
LOGIN_REDIRECT_URL = '/'  # Куда перенаправлять после успешного входа (например, на главную)
LOGOUT_REDIRECT_URL = '/' # Куда перенаправлять после выхода (например, на главную)


# EMAIL settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config.mail.host              # SMTP-сервер
EMAIL_PORT = config.mail.port               # Порт для TLS
EMAIL_USE_TLS = config.mail.tls            # Использовать TLS (True для порта 587)
EMAIL_USE_SSL = config.mail.ssl            # Не использовать SSL (True для порта 465)
EMAIL_HOST_USER = config.mail.user         # Ваш email
EMAIL_HOST_PASSWORD = config.mail.password # Пароль приложения (не основной пароль!)
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER       # Email отправителя по умолчанию
